on:
  schedule:
    - cron: "15 5 * * *"
  workflow_dispatch:

jobs:
  octocat_hello-world:
    runs-on: ubuntu-latest
    name: Sample job using octocat/hello-world
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v1

      - name: issue2atom
        id: issue2atom1
        uses: tsubasaogawa/issue2atom@v3
        with:
          user: "xueyuanl"
          repo: "daily-hackernews"
          max_issue_num: 10

      - name: issue2atom
        id: issue2atom2
        uses: tsubasaogawa/issue2atom@v3
        with:
          user: "tsubasaogawa"
          repo: "atoms"
          max_issue_num: 10
          
      - name: issue2atom
        id: issue2atom3
        uses: tsubasaogawa/issue2atom@v3
        with:
          user: "octocat"
          repo: "hello-world"
          max_issue_num: 10

      - name: Push generated atom file
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generate ${{ steps.issue2atom1.outputs.atom_file_path }} (${{ steps.issue2atom1.outputs.atom_file_size }} bytes)
          branch: gh-pages
          file_pattern: "**/atom.xml"
          create_branch: true
          push_options: "--force"
